### ISSUE TITLE
Support only for two SD insta 8xxx types fully

### ISSUE THREAD

**Issue by brunorolak** [Colt-Enigma/platform_device_qcom_sepolicy-legacy-um#1]
Here only have two SD support:
710 and 845
Insta 8xxx: 
8937
8953
8996
8998
And sdm660

My device uses 8996 and get a lots of errors on sepolicy and after add 25 lines on file.te to solve, one friend from PE core team ask me for why I'm build unstoppable, and ask me to see the tree, and no errors on tree, the he point me here is the problem, these support only the two SD

**Comment by schardev** [comment]
Yeah. We accidentally mismerged `sepolicy-legacy-um` with `sepolicy_vndr`. 

It should be fixed now. Just force sync and build again.
